#!/bin/sh

### Command Gmsh ###

## converter *.geo > *.msh

gmsh stator_im.geo -2 -o im_stator.msh

gmsh rotor_im.geo -2 -o rotor_im.msh

### Command Elmer ###

## converter *.msh > mesh.*

ElmerGrid 14 2 stator_im.msh -2d –autoclean –names

ElmerGrid 14 2 rotor_im.msh -2d -autoclean -names

## Unite meshes

ElmerGrid 2 2 stator_im in rotor_im -unite -autoclean -names -out motor_im

## Run case_02_Mumps

ElmerSolver case_02_Mumps.sif

#------------------------------------------------------------------------------
